version: "3.1"
services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./scripts/create_table.sql:/docker-entrypoint-initdb.d/create_table.sql