version: '3.7'
services:
  events_api:
    build: .
    image: mahfooz/events-api
    ports:
      - "5000:5000"
    networks:
      - airflow_net

networks:
  airflow_net:
    name:
      airflow_docker_default
    external: true
