@startuml "airflow architecture"

actor as user

[airflow webserver] as webserver

folder "dags folder" as folders

[airflow scheduler] as scheduler

database "metasore"

file "dag file" as dagfile1
file "dag file" as dagfile2
file "dag file" as dagfile3

[workers]

queue "Queues"

user -r-> webserver : "Monitor DAG runs + result"

folders -u-> scheduler : "Read dags"

scheduler -u-> metasore : "Store serlialized dags"

metasore -l-> webserver : ""

scheduler -r-> Queues : "Schedule tasks"

Queues -u-> workers : "Execute the tasks"

workers -l-> metasore : "Store the task results"

dagfile1 <-u- folders
dagfile2 <-u- folders
dagfile3 <-u- folders

user -d-> folders : "Write data worflows in python as dag"

@enduml