version: "3.1"
services:  
  wiki_results:
      image: postgres:13
      environment:
        - POSTGRES_USER=airflow
        - POSTGRES_PASSWORD=airflow
        - POSTGRES_DB=airflow
      ports:
        - "5433:5432"
      volumes:
        - ./scripts/create_table.sql:/docker-entrypoint-initdb.d/create_table.sql
      networks:
        - airflow_net

networks:
  airflow_net:
    name:
      airflow_docker_default
    external: true